language: c

sudo: required

env:
  - TEST_SUITE=pipeline-noinput
  - TEST_SUITE=pipeline-input
  - TEST_SUITE=CRAN

before_install:
  - mkdir bin
  - pushd bin
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigInfo
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigToBedGraph
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 *
  - export PATH=$(pwd):$PATH
  - popd
  - travis-tool.sh bootstrap
  - sudo apt-get install -y bedtools libdb5.1++-dev libdb5.1-stl-dev texlive

install:
  - travis-tool.sh r_install devtools RJSONIO hexbin xtable future directlabels
  - travis-tool.sh install_deps
  - Rscript -e "devtools::install(dependencies=FALSE)"

script:
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_failure:
  - travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

