#define ERROR_COVERAGE_CANT_OPEN_INPUT_FILE 1
#define ERROR_COVERAGE_UNEXPECTED_INPUT 2
#define ERROR_COVERAGE_NON_INTEGER 3
#define ERROR_COVERAGE_NEGATIVE 4
int coverage(char *bedGraph_file, double *);

